projektInz.web/Controllers/KontrahenciController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using projektInz.biznes;
using projektInz.dane;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, sprzedawca, kasjer")]
    public class KontrahenciController : Controller
    {
        public ActionResult Index()
        {
            List<Kontrahent> allKontrahent;
            using (var dane = new KontekstDanych())
            {
                allKontrahent = dane.Kontrahenci.ToList();
            }

            var widoki = allKontrahent.Select(kontrahent => new WidokKontrahent
            {
                Id = kontrahent.Id,
                Imię = kontrahent.Imię,
                Nazwisko = kontrahent.Nazwisko,
                NazwaFirmy = kontrahent.NazwaFirmy,
                Nip = kontrahent.Nip,
                Adres = kontrahent.Adres,
                NrTel = kontrahent.NrTel,
                Email = kontrahent.Email
            }).ToList();

            return View(widoki);
        }

        public ActionResult DodajKontrahenta()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DodajKontrahenta(NowyKontrahent nowyKontrahent)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var kontrahent = new Kontrahent(
                    nowyKontrahent.Imię,
                    nowyKontrahent.Nazwisko,
                    nowyKontrahent.NazwaFirmy,
                    nowyKontrahent.Nip,
                    nowyKontrahent.Adres,
                    nowyKontrahent.NrTel,
                    nowyKontrahent.Email
                    );
                dane.Kontrahenci.Add(kontrahent);
                dane.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult EdytujKontrahent(int id)
        {
            Kontrahent kontrahent;
            using (var dane = new KontekstDanych())
            {
                kontrahent = dane.Kontrahenci.Single(x => x.Id == id);
            }
            return View(new WidokKontrahent
            {
                Imię = kontrahent.Imię,
                Nazwisko = kontrahent.Nazwisko,
                NazwaFirmy = kontrahent.NazwaFirmy,
                Nip = kontrahent.Nip,
                Adres = kontrahent.Adres,
                NrTel = kontrahent.NrTel,
                Email = kontrahent.Email
            });
        }

        [HttpPost]
        public ActionResult EdytujKontrahent(EdytowanyKontrahent edytowanyKontrahent)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var kontrahent = dane.Kontrahenci.Single(x => x.Id == edytowanyKontrahent.Id);

                kontrahent.ZmienKontrahent(edytowanyKontrahent.Imię,
                    edytowanyKontrahent.Nazwisko,
                    edytowanyKontrahent.NazwaFirmy,
                    edytowanyKontrahent.Adres,
                    edytowanyKontrahent.Nip,
                    edytowanyKontrahent.NrTel,
                    edytowanyKontrahent.Email);
                dane.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

projektInz.web/Views/Kontrahenci/DodajKontrahenta.cshtml
@model projektInz.web.Models.NowyKontrahent

@{
    ViewBag.Title = "Dodaj kontrahenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj Kontrahenta</h2>
@using (Html.BeginForm("DodajKontrahenta", "Kontrahenci", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.Imię)
        @Html.TextBoxFor(m => m.Imię, new { @class = "form-control", placeholder = "Wprowadź imię" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwisko)
        @Html.TextBoxFor(m => m.Nazwisko, new { @class = "form-control", placeholder = "Wprowadź nazwisko" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NazwaFirmy, "Nazwa Firmy")
        @Html.TextBoxFor(m => m.NazwaFirmy, new { @class = "form-control", placeholder = "Wprowadz nazwę firmy" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nip, "NIP")
        @Html.TextBoxFor(m => m.Nip, new { @class = "form-control", placeholder = "Podaj numer NIP" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres, new { @class = "form-control", placeholder = "Podaj adres firmy" })
    </div>  
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel, new { @class = "form-control", placeholder = "Podaj numer telefonu" })
    </div>  
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Podaj email firmy" })
    </div>  
       
    <input type="submit" class="btn btn-default" value="Dodaj" />
}

projektInz.web/Views/Kontrahenci/EdytujKontrahent.cshtml
@model projektInz.web.Models.WidokKontrahent

@{
    ViewBag.Title = "Edytuj Kontrahenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Kontrahenta</h2>

@using (Html.BeginForm("EdytujKontrahent", "Kontrahenci", FormMethod.Post, new {role = "form"} ))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Imię)
        @Html.TextBoxFor(m => m.Imię,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwisko)
        @Html.TextBoxFor(m => m.Nazwisko,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NazwaFirmy, "Nazwa Firmy")
        @Html.TextBoxFor(m => m.NazwaFirmy,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nip, "NIP")
        @Html.TextBoxFor(m => m.Nip,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <input type="submit" value="Zapisz" />
}

projektInz.web/Views/Kontrahenci/Index.cshtml
@model System.Collections.Generic.List<projektInz.web.Models.WidokKontrahent>

@{
    ViewBag.Title = "Kontrahenci";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kontrahenci</h2>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Nazwa Firmy</th>
                <th>Adres</th>
                <th>Nip</th>
                <th>Nr. Telefonu</th>
                <th>E-mail</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kontr in this.Model)
            {
                <tr>
                    <td>@kontr.Imię</td>
                    <td>@kontr.Nazwisko</td>
                    <td>@kontr.NazwaFirmy</td>
                    <td>@kontr.Adres</td>
                    <td>@kontr.Nip</td>
                    <td>@kontr.NrTel</td>
                    <td>@kontr.Email</td>
                    <td>@Html.ActionLink("Edytuj","EdytujKontrahent",new { id = kontr.Id })</td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.ActionLink("Dodaj","DodajKontrahenta")