projektInz.web/Controllers/FakturyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using projektInz.biznes;
using projektInz.dane;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, sprzedawca, kasjer")]
    public class FakturyController : Controller
    {
        public ActionResult Index(int id)
        {
            //Otworz polaczenie z baza danych
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                var klient = dane.Klienci.First(x => x.Id == id);
                var wszystkieFaktury = dane.Faktury.Where(x => x.Klient.Id == id).ToList();
                var faktury = wszystkieFaktury.Select(UtworzWidokFaktury).ToList();
                //Wyrenderuj widok na bazie modelu widoki

                return View(new FakturyKlienta
                {
                    Nazwa = klient.Nazwa,
                    Identyfikator = klient.Identyfikator,
                    Faktury = faktury
                });
            }
        }

        public ActionResult Drukuj(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var faktura = dane.Faktury.First(x => x.Id == id);
                return View(KonwertujDoWidoku(faktura));
            }
        }

        [Authorize(Roles = "admin, kasjer, magazynier")]
        public ActionResult DrukujWZ(int id, bool? useLayout = false)
        {
            using (var dane = new KontekstDanych())
            {
                var wz = dane.WZ.First(x => x.Id == id);
                ViewBag.NumerWZ = wz.Numer;
                ViewBag.UseLayout = useLayout;
                return View(KonwertujDoWidoku(wz.Faktura));
            }
        }

        private static WidokWydrukuFaktury KonwertujDoWidoku(Faktura faktura)
        {
            return new WidokWydrukuFaktury()
            {
                AdresKlienta = faktura.AdresKlienta,
                IdentyfikatorKlienta = faktura.NumerIdentyfikacyjnyKlienta,
                NazwaKlienta = faktura.NazwaKlienta,
                Numer = faktura.Numer,
                Podatek = faktura.Podatek,
                WartoscBrutto = faktura.WartoscBrutto,
                WartoscNetto = faktura.WartoscNetto,
                Pozycje = faktura.Pozycje.Select(poz => new WidokPozycjiFaktury()
                {
                    Produkt = poz.Produkt.Nazwa,
                    CenaBrutto = poz.CenaBrutto,
                    CenaNetto = poz.CenaNetto,
                    CenaJednostkowaNetto = poz.Produkt.CenaSprzedazyNetto,
                    Ilosc = poz.Ilosc,
                    JM = poz.Produkt.JM
                }).ToList()
            };
        }

        private static WidokFaktury UtworzWidokFaktury(Faktura faktura)
        {
            return new WidokFaktury()
            {
                Id = faktura.Id,
                Numer = faktura.Numer,
                IloscPozycji = faktura.Pozycje.Count,
                WartoscBrutto = faktura.WartoscBrutto,
                WartoscNetto = faktura.WartoscNetto,
            };
        }
    }
}

projektInz.web/Controllers/ZamowieniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web.Mvc;
using projektInz.biznes;
using projektInz.dane;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, sprzedawca, kasjer")]
    public class ZamowieniaController : Controller
    {
        public ActionResult Index(int? wzId = null)
        {
            List<Zamowienie> wszystkieZamowienia;
            //Otworz polaczenie z baza danych
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                wszystkieZamowienia = dane.Zamowienia.ToList();
                var widoki = wszystkieZamowienia.Select(UtworzWidokZamowienia).ToList();
                //Wyrenderuj widok na bazie modelu widoki
                ViewBag.WzId = wzId;
                return View(widoki);
            }
        }

        private static WidokZamowienia UtworzWidokZamowienia(Zamowienie zamowienie)
        {
            return new WidokZamowienia()
            {
                Id = zamowienie.Id,
                Stan = zamowienie.Stan.ToString(),
                Numer = zamowienie.Id.ToString(),
                IloscPozycji = zamowienie.Pozycje.Count,
                WartoscBrutto = zamowienie.WartoscBrutto,
                WartoscNetto = zamowienie.WartoscNetto,
                WZ = zamowienie.WZ != null ? zamowienie.WZ.Id : -1
            };
        }
        private EdytowaneZamowienie UtworzEdytowaneZamowienie(Zamowienie zamowienie, IEnumerable<Produkt> produkty)
        {
            return new EdytowaneZamowienie
            {
                Stan = zamowienie.Stan.ToString(),
                MoznaAnulowac = zamowienie.MoznaAnulowac && User.IsInRole("sprzedawca"),
                MoznaEdytowac = zamowienie.MoznaEdytowac && User.IsInRole("sprzedawca"),
                MoznaOplacic = zamowienie.MoznaOplacic && User.IsInRole("kasjer"),
                MoznaZatwierdzic = zamowienie.MoznaZatwierdzic && User.IsInRole("sprzedawca"),
                MoznaZrealizowac = zamowienie.MoznaZrealizowac && User.IsInRole("magazynier"),
                Produkty = produkty.Select(x => new SelectListItem()
                {
                    Text = x.Nazwa,
                    Value = x.Id.ToString()
                }).ToList(),
                Id = zamowienie.Id,
                Numer = zamowienie.Id.ToString(),
                Pozycje = zamowienie.Pozycje.Select(pozycja => new WidokPozycjiZamowienia()
                {
                    Produkt = pozycja.Produkt.Nazwa,
                    CenaJednostkowaNetto = pozycja.Produkt.CenaSprzedazyNetto,
                    Ilosc = pozycja.Ilosc,
                    CenaNetto = pozycja.CenaNetto,
                    CenaBrutto = pozycja.CenaBrutto,
                    StawkaVat = (int) (pozycja.Produkt.StawkaVat * 100),
                    Numer = pozycja.Numer
                }).ToList()
            };
        }

        [Authorize(Roles = "sprzedawca")]
        public ActionResult DodajZamowienie(int id)
        {
            Zamowienie zamowienie;
            using (var dane = new KontekstDanych())
            {
                //Pobranie klienta
                var klient = dane.Klienci.First(x => x.Id == id);
                zamowienie = klient.UtworzZamowienie();
                dane.Zamowienia.Add(zamowienie);
                dane.SaveChanges();
            }
            return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
        }

        [Authorize(Roles = "sprzedawca, kasjer, magazynier")]
        public ActionResult EdytujZamowienie(int id)
        {
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var widok = UtworzEdytowaneZamowienie(zamowienie, dane.Produkty);
                return View(widok);
            }
        }


        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult DodajPozycje(NowaPozycja nowaPozycja)
        {

            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == nowaPozycja.Id);
                var produkt = dane.Produkty.First(x => x.Id == nowaPozycja.IdProduktu);

                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                if (!zamowienie.MoznaDodacPozycje(produkt, nowaPozycja.Ilosc))
                {
                    ModelState.AddModelError("Ilosc", "Brak wymaganej ilości towaru na magazynie. Dostępne "+produkt.Stan);
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                zamowienie.DodajPozycje(produkt, nowaPozycja.Ilosc);

                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult AktualizujPozycje(ZaktualizowanaPozycja zaktualizowanaPozycja)
        {

            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == zaktualizowanaPozycja.Id);
                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }

                int ilosc;
                if (!int.TryParse(zaktualizowanaPozycja.Ilosc[zaktualizowanaPozycja.Numer.ToString()], out ilosc))
                {
                    ModelState.AddModelError("Ilosc[" + zaktualizowanaPozycja.Numer + "]", "Ilość musi być poprawną liczbą.");
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                if (!zamowienie.MoznaAktualizowacPozycje(zaktualizowanaPozycja.Numer, ilosc))
                {
                    var pozycja = zamowienie.Pozycje.First(x => x.Numer == zaktualizowanaPozycja.Numer);
                    ModelState.AddModelError("Ilosc[" + zaktualizowanaPozycja.Numer + "]", "Brak wymaganej ilości towaru na magazynie. Dostępne " + pozycja.Produkt.Stan);
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                zamowienie.AktualizujPozycje(zaktualizowanaPozycja.Numer, ilosc);

                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult UsunPozycje(UsunietaPozycja usunietaPozycja)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == usunietaPozycja.Id);
                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                var usunieta = zamowienie.UsunPozycje(usunietaPozycja.Numer);
                dane.PozycjeZamowien.Remove(usunieta);
                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult Zatwierdz(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var generator = dane.GeneratoryNumerowFaktur.First();
                var faktura = zamowienie.Zatwierdz(generator);
                dane.Faktury.Add(faktura);
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "kasjer")]
        public ActionResult Oplacono(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var wz = zamowienie.Oplacono();
                dane.WZ.Add(wz);
                dane.SaveChanges();
                return RedirectToAction("Index",new {wzId = wz.Id});
            }
        }

        [HttpPost]
        [Authorize(Roles = "magazynier")]
        public ActionResult Zrealizowano(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                zamowienie.Zrealizowano();
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult Anuluj(int id)
        {
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                zamowienie.Anuluj();
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

projektInz.web/Views/Zamowienia/EdytujZamowienie.cshtml
@model projektInz.web.Models.EdytowaneZamowienie

@{
    ViewBag.Title = "Zamówienie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h2>Zamówienie nr @Model.Numer (@Model.Stan)</h2>
        @if (Model.MoznaAnulowac)
        {
            using (Html.BeginForm("Anuluj", "Zamowienia", FormMethod.Post, new {role = "form"}))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <input type="submit" value="Anuluj"/>
            }
        }
        @if (Model.MoznaZatwierdzic)
        {
            using (Html.BeginForm("Zatwierdz", "Zamowienia", FormMethod.Post, new {role = "form"}))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <input type="submit" value="Zatwierdź"/>
            }
        }
        @if (Model.MoznaOplacic)
        {
            using (Html.BeginForm("Oplacono", "Zamowienia", FormMethod.Post, new {role = "form"}))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <input type="submit" value="Oplacono"/>
            }
        }
        @if (Model.MoznaZrealizowac)
        {
            using (Html.BeginForm("Zrealizowano", "Zamowienia", FormMethod.Post, new {role = "form"}))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <input type="submit" value="Zrealizowano"/>
            }
        }
        <h3>Pozycje</h3>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Produkt</th>
                        <th>Ilość</th>
                        <th>Cena jednostkowa netto</th>
                        <th>Cena netto</th>
                        <th>Cena brutto</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="zamowienia">
                    @foreach (var pozycja in this.Model.Pozycje)
                    {
                        <tr>
                            <td>@pozycja.Produkt</td>
                            <td>
                                @if (Model.MoznaEdytowac)
                                {
                                    using (Html.BeginForm("AktualizujPozycje", "Zamowienia", FormMethod.Post, new {role = "form"}))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.Hidden("Id", Model.Id)
                                        @Html.Hidden("Numer", pozycja.Numer)
                                        @Html.TextBox("Ilosc[" + pozycja.Numer + "]", pozycja.Ilosc)
                                        <input type="submit" value="Aktualizuj"/>
                                    }
                                }
                                else
                                {
                                    <span>@pozycja.Ilosc</span>
                                }
                            </td>
                            <td>@pozycja.CenaJednostkowaNetto.ToString("#.00")</td>
                            <td>@pozycja.CenaNetto.ToString("#.00")</td>
                            <td>@pozycja.CenaBrutto.ToString("#.00")</td>
                            <td>
                                @if (Model.MoznaEdytowac)
                                {
                                    using (Html.BeginForm("UsunPozycje", "Zamowienia", FormMethod.Post, new {role = "form"}))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.Hidden("Id", Model.Id)
                                        @Html.Hidden("Numer", pozycja.Numer)
                                        <input type="submit" value="Usuń"/>
                                    }
                                }
                            </td>
                        </tr>
                    }
                    <tr>
                        @if (Model.MoznaEdytowac)
                        {
                            using (Html.BeginForm("DodajPozycje", "Zamowienia", FormMethod.Post, new {role = "form"}))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary()
                                @Html.Hidden("Id", Model.Id)
                                <td>
                                    @Html.DropDownList("IdProduktu", Model.Produkty)                            
                                </td>
                                <td>
                                    @Html.TextBox("Ilosc")
                                </td>
                                <td></td>
                                <td></td>
                                <td><input type="submit" value="Dodaj"/></td>
                            }
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

projektInz.web/Views/Zamowienia/Index.cshtml
@model System.Collections.Generic.List<projektInz.web.Models.WidokZamowienia>

@{
    ViewBag.Title = "Zamówienia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h2>Zamówienia</h2>

        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Numer</th>
                        <th>Stan</th>
                        <th>Ilość pozycji</th>
                        <th>Wartość netto</th>
                        <th>Wartość brutto</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var zamowienie in this.Model)
                    {
                        <tr>
                            <td>@zamowienie.Numer</td>
                            <td>@zamowienie.Stan</td>
                            <td>@zamowienie.IloscPozycji</td>
                            <td>@zamowienie.WartoscNetto.ToString("##.00")</td>
                            <td>@zamowienie.WartoscBrutto.ToString("##.00")</td>
                            <td>@Html.ActionLink("Edytuj","EdytujZamowienie",new { id = zamowienie.Id }) 
                                @if (zamowienie.WZ != -1)
                                {
                                    <span>|</span>
                                    @Html.ActionLink("Drukuj WZ", "DrukujWZ", "Faktury", new {id = zamowienie.WZ}, new {target = "_blank", id="wz-"+zamowienie.WZ})
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts
{
    @if (ViewBag.WzId != null)
    {
        <script>
            $(function() {
                var link = $('#wz-@ViewBag.WzId');
                var target = link.attr("target");
                var win = window.open(link.attr("href"), target);
                win.focus();
            });
        </script>
    }
}