projektInz.web/Controllers/KlienciController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using projektInz.biznes;
using projektInz.dane;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, sprzedawca, kasjer")]
    public class KlienciController : Controller
    {
        //
        // GET: /Customers/

        public ActionResult Index()
        {
            List<Klient> wszyscyKlienci;
            using (var dane = new KontekstDanych())
            {
                wszyscyKlienci = dane.Klienci.ToList();
            }

            var widoki = wszyscyKlienci.Select(klient => new WidokKlienta
            {
                Id = klient.Id,
                Nazwa = klient.Nazwa,
                PeselNip = klient.Identyfikator,
                Adres = klient.Adres,
                NrTel = klient.NrTel,
                Email = klient.Email
            }).ToList();

            return View(widoki);
        }
        public ActionResult DodajKlienta()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DodajKlienta(NowyKlient nowyKlient)
        {
            if (nowyKlient.TypKlienta == TypKlienta.Firma)
            {
                if (string.IsNullOrWhiteSpace(nowyKlient.NazwaFirmy))
                {
                    ModelState.AddModelError("NazwaFirmy","Nazwa firmy jest wymagana.");
                }
                if (string.IsNullOrWhiteSpace(nowyKlient.Nip))
                {
                    ModelState.AddModelError("Nip", "Numer NIP jest wymagany.");
                }
            }
            else if (nowyKlient.TypKlienta == TypKlienta.OsobaPrywatna)
            {
                if (string.IsNullOrWhiteSpace(nowyKlient.Imie))
                {
                    ModelState.AddModelError("Imie", "Imie jest wymagane.");
                }
                if (string.IsNullOrWhiteSpace(nowyKlient.Nazwisko))
                {
                    ModelState.AddModelError("Nazwisko", "Nazwisko jest wymagane.");
                }
                if (string.IsNullOrWhiteSpace(nowyKlient.Pesel))
                {
                    ModelState.AddModelError("Pesel", "Pesel jest wymagany.");
                }
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            using (var dane = new KontekstDanych())
            {
                var klient = new Klient(
                    nowyKlient.TypKlienta,
                    nowyKlient.Imie,
                    nowyKlient.Nazwisko,
                    nowyKlient.Pesel,
                    nowyKlient.NazwaFirmy,
                    nowyKlient.Nip,
                    nowyKlient.Adres,
                    nowyKlient.NrTel,
                    nowyKlient.Email
                    );
                dane.Klienci.Add(klient);
                dane.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult EdytujKlienta(int id)
        {
            Klient klient;
            using (var dane = new KontekstDanych())
            {
                klient = dane.Klienci.Single(x => x.Id == id);
            }
            if (klient.Typ == TypKlienta.Firma)
            {
                return View("EdytujFirme", new WidokFirmy
                {
                    NazwaFirmy = klient.NazwaFirmy,
                    Nip = klient.Nip,
                    Adres = klient.Adres,
                    NrTel = klient.NrTel,
                    Email = klient.Email
                });
            }
            return View("EdytujOsobePrywatna", new WidokOsobyPrywatnej
            {
                Imie = klient.Imie,
                Nazwisko = klient.Nazwisko,
                Pesel = klient.Pesel,
                Adres = klient.Adres,
                NrTel = klient.NrTel,
                Email = klient.Email
            });
        }

        [HttpPost]
        public ActionResult EdytujOsobePrywatna(EdytowanaOsobaPrywatna osobaPrywatna)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var klient = dane.Klienci.Single(x => x.Id == osobaPrywatna.Id);

                klient.ModyfikujDaneOsobyPrywatnej(osobaPrywatna.Imie,
                    osobaPrywatna.Nazwisko,
                    osobaPrywatna.Adres,
                    osobaPrywatna.NrTel,
                    osobaPrywatna.Email);
                dane.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult EdytujFirme(EdytowanaFirma edytowanaFirma)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var klient = dane.Klienci.Single(x => x.Id == edytowanaFirma.Id);

                klient.ModyfikujDaneFirmy(
                    edytowanaFirma.NazwaFirmy,
                    edytowanaFirma.Adres,
                    edytowanaFirma.NrTel,
                    edytowanaFirma.Email);
                dane.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

projektInz.web/Controllers/ZamowieniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web.Mvc;
using projektInz.biznes;
using projektInz.dane;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, sprzedawca, kasjer")]
    public class ZamowieniaController : Controller
    {
        public ActionResult Index(int? wzId = null)
        {
            List<Zamowienie> wszystkieZamowienia;
            //Otworz polaczenie z baza danych
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                wszystkieZamowienia = dane.Zamowienia.ToList();
                var widoki = wszystkieZamowienia.Select(UtworzWidokZamowienia).ToList();
                //Wyrenderuj widok na bazie modelu widoki
                ViewBag.WzId = wzId;
                return View(widoki);
            }
        }

        private static WidokZamowienia UtworzWidokZamowienia(Zamowienie zamowienie)
        {
            return new WidokZamowienia()
            {
                Id = zamowienie.Id,
                Stan = zamowienie.Stan.ToString(),
                Numer = zamowienie.Id.ToString(),
                IloscPozycji = zamowienie.Pozycje.Count,
                WartoscBrutto = zamowienie.WartoscBrutto,
                WartoscNetto = zamowienie.WartoscNetto,
                WZ = zamowienie.WZ != null ? zamowienie.WZ.Id : -1
            };
        }
        private EdytowaneZamowienie UtworzEdytowaneZamowienie(Zamowienie zamowienie, IEnumerable<Produkt> produkty)
        {
            return new EdytowaneZamowienie
            {
                Stan = zamowienie.Stan.ToString(),
                MoznaAnulowac = zamowienie.MoznaAnulowac && User.IsInRole("sprzedawca"),
                MoznaEdytowac = zamowienie.MoznaEdytowac && User.IsInRole("sprzedawca"),
                MoznaOplacic = zamowienie.MoznaOplacic && User.IsInRole("kasjer"),
                MoznaZatwierdzic = zamowienie.MoznaZatwierdzic && User.IsInRole("sprzedawca"),
                MoznaZrealizowac = zamowienie.MoznaZrealizowac && User.IsInRole("magazynier"),
                Produkty = produkty.Select(x => new SelectListItem()
                {
                    Text = x.Nazwa,
                    Value = x.Id.ToString()
                }).ToList(),
                Id = zamowienie.Id,
                Numer = zamowienie.Id.ToString(),
                Pozycje = zamowienie.Pozycje.Select(pozycja => new WidokPozycjiZamowienia()
                {
                    Produkt = pozycja.Produkt.Nazwa,
                    CenaJednostkowaNetto = pozycja.Produkt.CenaSprzedazyNetto,
                    Ilosc = pozycja.Ilosc,
                    CenaNetto = pozycja.CenaNetto,
                    CenaBrutto = pozycja.CenaBrutto,
                    StawkaVat = (int) (pozycja.Produkt.StawkaVat * 100),
                    Numer = pozycja.Numer
                }).ToList()
            };
        }

        [Authorize(Roles = "sprzedawca")]
        public ActionResult DodajZamowienie(int id)
        {
            Zamowienie zamowienie;
            using (var dane = new KontekstDanych())
            {
                //Pobranie klienta
                var klient = dane.Klienci.First(x => x.Id == id);
                zamowienie = klient.UtworzZamowienie();
                dane.Zamowienia.Add(zamowienie);
                dane.SaveChanges();
            }
            return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
        }

        [Authorize(Roles = "sprzedawca, kasjer, magazynier")]
        public ActionResult EdytujZamowienie(int id)
        {
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var widok = UtworzEdytowaneZamowienie(zamowienie, dane.Produkty);
                return View(widok);
            }
        }


        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult DodajPozycje(NowaPozycja nowaPozycja)
        {

            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == nowaPozycja.Id);
                var produkt = dane.Produkty.First(x => x.Id == nowaPozycja.IdProduktu);

                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                if (!zamowienie.MoznaDodacPozycje(produkt, nowaPozycja.Ilosc))
                {
                    ModelState.AddModelError("Ilosc", "Brak wymaganej ilości towaru na magazynie. Dostępne "+produkt.Stan);
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                zamowienie.DodajPozycje(produkt, nowaPozycja.Ilosc);

                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult AktualizujPozycje(ZaktualizowanaPozycja zaktualizowanaPozycja)
        {

            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == zaktualizowanaPozycja.Id);
                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }

                int ilosc;
                if (!int.TryParse(zaktualizowanaPozycja.Ilosc[zaktualizowanaPozycja.Numer.ToString()], out ilosc))
                {
                    ModelState.AddModelError("Ilosc[" + zaktualizowanaPozycja.Numer + "]", "Ilość musi być poprawną liczbą.");
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                if (!zamowienie.MoznaAktualizowacPozycje(zaktualizowanaPozycja.Numer, ilosc))
                {
                    var pozycja = zamowienie.Pozycje.First(x => x.Numer == zaktualizowanaPozycja.Numer);
                    ModelState.AddModelError("Ilosc[" + zaktualizowanaPozycja.Numer + "]", "Brak wymaganej ilości towaru na magazynie. Dostępne " + pozycja.Produkt.Stan);
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                zamowienie.AktualizujPozycje(zaktualizowanaPozycja.Numer, ilosc);

                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult UsunPozycje(UsunietaPozycja usunietaPozycja)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == usunietaPozycja.Id);
                if (!ModelState.IsValid)
                {
                    return View("EdytujZamowienie", UtworzEdytowaneZamowienie(zamowienie, dane.Produkty));
                }
                var usunieta = zamowienie.UsunPozycje(usunietaPozycja.Numer);
                dane.PozycjeZamowien.Remove(usunieta);
                dane.SaveChanges();
                return RedirectToAction("EdytujZamowienie", new { id = zamowienie.Id });
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult Zatwierdz(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var generator = dane.GeneratoryNumerowFaktur.First();
                var faktura = zamowienie.Zatwierdz(generator);
                dane.Faktury.Add(faktura);
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "kasjer")]
        public ActionResult Oplacono(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                var wz = zamowienie.Oplacono();
                dane.WZ.Add(wz);
                dane.SaveChanges();
                return RedirectToAction("Index",new {wzId = wz.Id});
            }
        }

        [HttpPost]
        [Authorize(Roles = "magazynier")]
        public ActionResult Zrealizowano(int id)
        {
            using (var dane = new KontekstDanych())
            {
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                zamowienie.Zrealizowano();
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "sprzedawca")]
        public ActionResult Anuluj(int id)
        {
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                var zamowienie = dane.Zamowienia.First(x => x.Id == id);
                zamowienie.Anuluj();
                dane.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

projektInz.web/Views/Klienci/DodajKlienta.cshtml
@model projektInz.web.Models.NowyKlient

@{
    ViewBag.Title = "Dodaj klienta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj Klienta</h2>
@using (Html.BeginForm("DodajKlienta", "Klienci", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div role="tabpanel">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="typ">
            <li role="presentation" class="active">
                <a href="#_firma" id="firma" aria-controls="_firma" role="tab" data-toggle="tab">Firma</a>
            </li>
            <li role="presentation">
                <a href="#_osobaPrywatna" id="osobaPrywatna" aria-controls="_osobaPrywatna" role="tab" data-toggle="tab">Osoba prywatna</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="_firma">
                <div class="form-group">
                    @Html.LabelFor(m => m.NazwaFirmy, "Nazwa Firmy")
                    @Html.TextBoxFor(m => m.NazwaFirmy, new { @class = "form-control", placeholder = "Wprowadz nazwę firmy" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Nip, "NIP")
                    @Html.TextBoxFor(m => m.Nip, new { @class = "form-control", placeholder = "Podaj numer NIP" })
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="_osobaPrywatna">
                <div class="form-group">
                    @Html.LabelFor(m => m.Imie)
                    @Html.TextBoxFor(m => m.Imie, new { @class = "form-control", placeholder = "Wprowadź imię" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Nazwisko)
                    @Html.TextBoxFor(m => m.Nazwisko, new { @class = "form-control", placeholder = "Wprowadź nazwisko" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Pesel)
                    @Html.TextBoxFor(m => m.Pesel, new { @class = "form-control", placeholder = "Wprowadź PESEL" })
                </div>
            </div>
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres, new { @class = "form-control", placeholder = "Podaj adres" })
    </div>  
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel, new { @class = "form-control", placeholder = "Podaj numer telefonu" })
    </div>  
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Podaj email" })
    </div>  
    @Html.Hidden("typKlienta","firma",new {id = "typKlienta"})
    <input type="submit" class="btn btn-default" value="Dodaj" />
}
@section scripts
{
    <script>
        $(function() {
            $('#typ #' + $('#typKlienta').val()).tab('show');
        });
        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
            $('#typKlienta').val(e.target.id);
        });
    </script>
}

projektInz.web/Views/Klienci/EdytujFirme.cshtml
@model projektInz.web.Models.WidokFirmy

@{
    ViewBag.Title = "Edytuj klienta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Klienta</h2>

@using (Html.BeginForm("EdytujFirme", "Klienci", FormMethod.Post, new {role = "form"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.NazwaFirmy, "Nazwa Firmy")
        @Html.TextBoxFor(m => m.NazwaFirmy,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <input type="submit" value="Zapisz" />
}

projektInz.web/Views/Klienci/EdytujKlienta.cshtml
@model projektInz.web.Models.WidokKlienta

@{
    ViewBag.Title = "Edytuj klienta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Klienta</h2>

@using (Html.BeginForm("EdytujKlienta", "Klienci", FormMethod.Post, new {role = "form"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Imie)
        @Html.TextBoxFor(m => m.Imie,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwisko)
        @Html.TextBoxFor(m => m.Nazwisko,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
        <div class="form-group">
        @Html.LabelFor(m => m.Pesel)
        @Html.TextBoxFor(m => m.Pesel,new { @class = "form-control", placeholder = "Wprowadź PESEL" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NazwaFirmy, "Nazwa Firmy")
        @Html.TextBoxFor(m => m.NazwaFirmy,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nip, "NIP")
        @Html.TextBoxFor(m => m.Nip,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <input type="submit" value="Zapisz" />
}

projektInz.web/Views/Klienci/EdytujOsobePrywatna.cshtml
@model projektInz.web.Models.WidokOsobyPrywatnej

@{
    ViewBag.Title = "Edytuj klienta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Klienta</h2>

@using (Html.BeginForm("EdytujOsobePrywatna", "Klienci", FormMethod.Post, new {role = "form"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Imie)
        @Html.TextBoxFor(m => m.Imie,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwisko)
        @Html.TextBoxFor(m => m.Nazwisko,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Adres)
        @Html.TextBoxFor(m => m.Adres,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NrTel, "Numer Telefonu")
        @Html.TextBoxFor(m => m.NrTel,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email,new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <input type="submit" value="Zapisz" />
}

projektInz.web/Views/Klienci/Index.cshtml
@model System.Collections.Generic.List<projektInz.web.Models.WidokKlienta>

@{
    ViewBag.Title = "Klienci";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Klienci</h2>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Pesel/NIP</th>
                <th>Adres</th>
                <th>Nr. Telefonu</th>
                <th>E-mail</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var klient in this.Model)
            {
                <tr>
                    <td>@klient.Nazwa</td>
                    <td>@klient.PeselNip</td>
                    <td>@klient.Adres</td>
                    <td>@klient.NrTel</td>
                    <td>@klient.Email</td>
                    <td>
                        @Html.ActionLink("Edytuj", "EdytujKlienta", new { id = klient.Id }) |
                        @Html.ActionLink("Nowe zamówienie", "DodajZamowienie", "Zamowienia", new { id = klient.Id }, null) |
                        @Html.ActionLink("Faktury", "Index", "Faktury", new { id = klient.Id }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.ActionLink("Dodaj","DodajKlienta")
    