projektInz.web/Controllers/ProduktyController.cs
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;
using projektInz.biznes;
using projektInz.dane;
using System.Linq;
using projektInz.web.Models;

namespace projektInz.web.Controllers
{
    [Authorize(Roles = "admin, magazynier")]
    public class ProduktyController : Controller
    {
        public ActionResult Index()
        {
            List<Produkt> wszystkieProdukty;
            //Otworz polaczenie z baza danych
            using (var dane = new KontekstDanych())
            {
                //Pobranie
                wszystkieProdukty = dane.Produkty.ToList();
            }

            var widoki = wszystkieProdukty.Select(KonwertujProdukt).ToList();
            //Wyrenderuj widok na bazie modelu widoki
            return View(widoki);
        }

        private WidokProduktu KonwertujProdukt(Produkt produkt)
        {
            return new WidokProduktu
            {
                Id = produkt.Id,
                Nazwa = produkt.Nazwa,
                DataWprowadzenia = produkt.DataWprowadzenia.ToShortDateString(),
                CenaSprzedazyNetto = produkt.CenaSprzedazyNetto,
                CenaZakupuNetto = produkt.CenaZakupuNetto,
                Grupa = produkt.Grupa,
                JM = produkt.JM,
                Stan = produkt.Stan,
                StawkaVat = (int) (produkt.StawkaVat * 100),
                Marza = (int)(produkt.Marza * 100)
            };
        }

        public ActionResult EdytujProdukt(int id)
        {
            Produkt produkt;
            using (var dane = new KontekstDanych())
            {
                produkt = dane.Produkty.Single(x => x.Id == id);
            }
            return View(KonwertujProdukt(produkt));
        }

        [HttpPost]
        public ActionResult EdytujProdukt(EdytowanyProdukt edytowanyProdukt)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var produkt = dane.Produkty.Single(x => x.Id == edytowanyProdukt.Id);
                produkt.ZmienProdukt(edytowanyProdukt.Nazwa,
                    edytowanyProdukt.Grupa, 
                    edytowanyProdukt.JM, 
                    edytowanyProdukt.Stan, 
                    (decimal)edytowanyProdukt.StawkaVat / 100, 
                    edytowanyProdukt.CenaZakupuNetto,
                    (decimal)edytowanyProdukt.Marza / 100);

                //Wysyła zmiany do bazy
                dane.SaveChanges();
            }
            //Przenosi uzytkownika do innej akcji (index)
            return RedirectToAction("Index");
        }

        public ActionResult DodajProdukt()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DodajProdukt(NowyProdukt nowyProdukt)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            using (var dane = new KontekstDanych())
            {
                var produkt = new Produkt(nowyProdukt.Nazwa,
                    nowyProdukt.Grupa,
                    nowyProdukt.JM,
                    nowyProdukt.Stan,
                    (decimal)nowyProdukt.StawkaVat / 100,
                    nowyProdukt.CenaZakupuNetto,
                    (decimal)nowyProdukt.Marza / 100);
                //Dodaje nowy produkt do unit of work, ale jeszcze nie do bazy danych
                dane.Produkty.Add(produkt);
                //Wysyła zmiany do bazy
                dane.SaveChanges();
            }
            //Przenosi uzytkownika do innej akcji (index)
            return RedirectToAction("Index");
        }

        
    }
}

projektInz.web/Views/Produkty/DodajProdukt.cshtml
@model projektInz.web.Models.NowyProdukt

@{
    ViewBag.Title = "Dodaj produkt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj produkt</h2>
@using (Html.BeginForm("DodajProdukt", "Produkty", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwa)
        @Html.TextBoxFor(m => m.Nazwa, new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Grupa)
        @Html.TextBoxFor(m => m.Grupa, new { @class = "form-control", placeholder = "Wprowadź nazwę grupy produktu" })
    </div>    
    <div class="form-group">
        @Html.LabelFor(m => m.JM, "Jednostka Miary")
        @Html.TextBoxFor(m => m.JM, new { @class = "form-control", placeholder = "Wprowadź jednoskę miary (kg / ml / l)" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Stan)
        @Html.TextBoxFor(m => m.Stan, new { @class = "form-control", placeholder = "Wprowadz stan" })
    </div>    
    <div class="form-group">
        @Html.LabelFor(m => m.StawkaVat, "Stawka VAT w %")
        @Html.TextBoxFor(m => m.StawkaVat, new { @class = "form-control", placeholder = "Wprowadz stawkę VAT" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CenaZakupuNetto, "Cena Zakupu Netto")
        @Html.TextBoxFor(m => m.CenaZakupuNetto, new { @class = "form-control", placeholder = "Podaj cene zakupu towaru netto" })
    </div>    
    <div class="form-group">
        @Html.LabelFor(m => m.Marza, "Marża w %")
        @Html.TextBoxFor(m => m.Marza, new { @class = "form-control", placeholder = "Podaj marżę" })
    </div>
    <input type="submit" class="btn btn-default" value="Dodaj" />
}

projektInz.web/Views/Produkty/EdytujProdukt.cshtml
@model projektInz.web.Models.WidokProduktu

@{
    ViewBag.Title = "Edytuj produkt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj produkt</h2>

@using (Html.BeginForm("EdytujProdukt", "Produkty", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    
    <div class="form-group">
        @Html.HiddenFor(m => m.Id)
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.Nazwa)
        @Html.TextBoxFor(m => m.Nazwa, new { @class = "form-control", placeholder = "Wprowadź nazwę" })
    </div>    
    
    <div class="form-group">
        @Html.LabelFor(m => m.Grupa)
        @Html.TextBoxFor(m => m.Grupa, new { @class = "form-control", placeholder = "Wprowadź nazwę grupy towaru" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.JM, "Jednostka Miary")
        @Html.TextBoxFor(m => m.JM, new { @class = "form-control", placeholder = "Wprowadź jednoskę miary (kg / ml / l)" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.Stan)
        @Html.TextBoxFor(m => m.Stan, new { @class = "form-control", placeholder = "Wprowadź stan" })
    </div>    
    
    <div class="form-group">
        @Html.LabelFor(m => m.StawkaVat, "Stawka VAT w %")
        @Html.TextBoxFor(m => m.StawkaVat, new { @class = "form-control", placeholder = "Wprowadź stawkę VAT" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.CenaZakupuNetto, "Cena Zakupu")
        @Html.TextBoxFor(m => m.CenaZakupuNetto, new { @class = "form-control", placeholder = "Wprowadź cene zakupu towaru netto" })
    </div>   
    <div class="form-group">
        @Html.LabelFor(m => m.Marza, "Marża w %")
        @Html.TextBoxFor(m => m.Marza, new { @class = "form-control", placeholder = "Wprowadź marżę" })
    </div> 
    <input type="submit" value="Dodaj" />
}

projektInz.web/Views/Produkty/Index.cshtml
@model System.Collections.Generic.List<projektInz.web.Models.WidokProduktu>

@{
    ViewBag.Title = "Produkty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h2>Produkty</h2>

        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nazwa Produktu</th>
                        <th>Stan</th>
                        <th>jm.</th>
                        <th>VAT (%)</th>
                        <th>Cena Zakupu Netto</th>
                        <th>Marża (%)</th>
                        <th>Cena Sprzedaży Netto</th>
                        <th>Data Wprowadzenia</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var prod in this.Model)
                    {
                        <tr>
                            <td>@prod.Id</td>
                            <td>@prod.Nazwa</td>
                            <td>@prod.Stan</td>
                            <td>@prod.JM</td>
                            <td>@prod.StawkaVat.ToString("## '%'")</td>
                            <td>@prod.CenaZakupuNetto.ToString("##.00")</td>
                            <td>@prod.Marza.ToString("## '%'")</td>
                            <td>@prod.CenaSprzedazyNetto.ToString("##.00")</td>
                            <td>@prod.DataWprowadzenia</td>
                            <td>
                                @Html.ActionLink("Edytuj","EdytujProdukt",new { id = prod.Id }) |
                                @Html.ActionLink("Zamów","Zamow","ZamowieniaProduktu" ,new { id = prod.Id }, null)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @Html.ActionLink("Dodaj","DodajProdukt")
    </div>
</div>